// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Checks that the database is reachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.R"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/rest.ServiceUnavailableResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.R"
                        }
                    }
                }
            }
        },
        "/v1/activities": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "lists published activities",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "child age in years (2..6)",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "language",
                            "motor",
                            "cognitive",
                            "social",
                            "emotional"
                        ],
                        "type": "string",
                        "description": "development goal",
                        "name": "goal",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.activityListView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/activities/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "returns a published activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "activity id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.activityView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/activities": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "lists all activities, including unpublished",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "child age in years (2..6)",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "language",
                            "motor",
                            "cognitive",
                            "social",
                            "emotional"
                        ],
                        "type": "string",
                        "description": "development goal",
                        "name": "goal",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.activityListView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "- title/description are required in both Uzbek (uz) and Russian (ru)\n- goal is one of: language, motor, cognitive, social, emotional\n- min_age/max_age are child ages in years, within 2..6",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "creates an activity",
                "parameters": [
                    {
                        "description": "activity",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CreateActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.activityView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/activities/{id}": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "returns an activity, including unpublished",
                "parameters": [
                    {
                        "type": "string",
                        "description": "activity id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.activityView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "lists users (soft-deleted users are excluded)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.userListView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "- phone_number is required, in E.164 format (+998901234567)\n- username is optional: 3..32 latin letters, digits, '_' or '.'; stored lowercase\n- name is optional, at most 100 characters; photo_id is an optional UUID\n- username and phone_number must be unique among non-deleted users (409)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "creates a user",
                "parameters": [
                    {
                        "description": "user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.userView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ConflictResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "returns a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.userView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Sets deleted_at; the user disappears from reads, their tokens are removed,\nand their username and phone number can be used again.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "soft-deletes a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.R"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.NotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "- only the fields present in the body change; omitted or null fields are kept\n- \"\" clears name, username or photo_id; phone_number cannot be cleared\n- same format and uniqueness rules as create",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "updates a user partially",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "fields to change",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.userView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.UnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.NotFoundResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ConflictResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/otp/send": {
            "post": {
                "description": "- phone_number: an Uzbek mobile number in E.164, +998 and 9 digits (422 otherwise)\n- purpose: sign_up (the number must not belong to a user, 409 otherwise) or update_user\n- ip_address: the end user's IPv4 or IPv6 address, used for rate limits\n- the code has 6 digits and is sent through Play Mobile; only its hash is stored\n- limits (429): one code per phone and purpose per resend_in seconds, and per hour at most\nOTP_MAX_PER_PHONE_HOUR codes per phone and OTP_MAX_PER_IP_HOUR per IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "otp"
                ],
                "summary": "sends a one-time code by SMS",
                "parameters": [
                    {
                        "description": "where and why to send the code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.SendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.R"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.sendOTPView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.BadRequestResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/rest.ConflictResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.UnprocessableContentResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/rest.TooManyRequestsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.InternalServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.BadRequestResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -11
                },
                "error_note": {
                    "type": "string",
                    "example": "limit must be a positive integer"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.ConflictResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -40
                },
                "error_note": {
                    "type": "string",
                    "example": "username is already taken"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.CreateActivityRequest": {
            "type": "object",
            "properties": {
                "description_ru": {
                    "type": "string",
                    "example": "Сортируйте камни по цвету"
                },
                "description_uz": {
                    "type": "string",
                    "example": "Toshlarni rangi bo'yicha saralang"
                },
                "duration_minutes": {
                    "type": "integer",
                    "maximum": 60,
                    "minimum": 1,
                    "example": 10
                },
                "goal": {
                    "type": "string",
                    "enum": [
                        "language",
                        "motor",
                        "cognitive",
                        "social",
                        "emotional"
                    ],
                    "example": "cognitive"
                },
                "is_published": {
                    "type": "boolean",
                    "example": true
                },
                "max_age": {
                    "type": "integer",
                    "maximum": 6,
                    "minimum": 2,
                    "example": 5
                },
                "min_age": {
                    "type": "integer",
                    "maximum": 6,
                    "minimum": 2,
                    "example": 3
                },
                "title_ru": {
                    "type": "string",
                    "example": "Цветные камни"
                },
                "title_uz": {
                    "type": "string",
                    "example": "Rangli toshlar"
                }
            }
        },
        "rest.CreateUserRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Dilnoza"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+998901234567"
                },
                "photo_id": {
                    "type": "string",
                    "example": "3f1d2c4b-8a9e-4b7c-9d2e-1a2b3c4d5e6f"
                },
                "username": {
                    "type": "string",
                    "example": "dilnoza_95"
                }
            }
        },
        "rest.InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -50
                },
                "error_note": {
                    "type": "string",
                    "example": "internal error"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.NotFoundResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -30
                },
                "error_note": {
                    "type": "string",
                    "example": "activity not found"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.R": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "$ref": "#/definitions/rest.errCode"
                },
                "error_note": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/rest.statusType"
                }
            }
        },
        "rest.SendOTPRequest": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string",
                    "example": "203.0.113.7"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+998901234567"
                },
                "purpose": {
                    "type": "string",
                    "enum": [
                        "sign_up",
                        "update_user"
                    ],
                    "example": "sign_up"
                }
            }
        },
        "rest.ServiceUnavailableResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -60
                },
                "error_note": {
                    "type": "string",
                    "example": "database unavailable"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.TooManyRequestsResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -70
                },
                "error_note": {
                    "type": "string",
                    "example": "a code was sent recently, request a new one in 42 seconds"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.UnauthorizedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -20
                },
                "error_note": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.UnprocessableContentResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.errCode"
                        }
                    ],
                    "example": -10
                },
                "error_note": {
                    "type": "string",
                    "example": "unknown goal \"flying\""
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.statusType"
                        }
                    ],
                    "example": "Failure"
                }
            }
        },
        "rest.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Dilnoza"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+998901234567"
                },
                "photo_id": {
                    "type": "string",
                    "example": "3f1d2c4b-8a9e-4b7c-9d2e-1a2b3c4d5e6f"
                },
                "username": {
                    "type": "string",
                    "example": "dilnoza_95"
                }
            }
        },
        "rest.activityListView": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.activityView"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "rest.activityView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "description_uz": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer",
                    "example": 10
                },
                "goal": {
                    "type": "string",
                    "example": "cognitive"
                },
                "id": {
                    "type": "string",
                    "example": "7b0c1f1e-2d7a-4d8e-9a55-0f4a0d7f9c11"
                },
                "is_published": {
                    "type": "boolean",
                    "example": true
                },
                "max_age": {
                    "type": "integer",
                    "example": 5
                },
                "min_age": {
                    "type": "integer",
                    "example": 3
                },
                "title_ru": {
                    "type": "string",
                    "example": "Цветные камни"
                },
                "title_uz": {
                    "type": "string",
                    "example": "Rangli toshlar"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "rest.errCode": {
            "type": "integer",
            "enum": [
                0,
                -10,
                -11,
                -20,
                -21,
                -30,
                -40,
                -50,
                -60,
                -70
            ],
            "x-enum-comments": {
                "_errCodeBadRequest": "for http 400",
                "_errCodeConflict": "for http 409",
                "_errCodeForbidden": "for http 403",
                "_errCodeInternalErr": "for http 500",
                "_errCodeNoError": "Success code.",
                "_errCodeNotFound": "for http 404",
                "_errCodeRateLimited": "for http 429",
                "_errCodeUnauthorized": "for http 401",
                "_errCodeUnavailable": "for http 503",
                "_errCodeValidation": "for http 422"
            },
            "x-enum-descriptions": [
                "Success code.",
                "for http 422",
                "for http 400",
                "for http 401",
                "for http 403",
                "for http 404",
                "for http 409",
                "for http 500",
                "for http 503",
                "for http 429"
            ],
            "x-enum-varnames": [
                "_errCodeNoError",
                "_errCodeValidation",
                "_errCodeBadRequest",
                "_errCodeUnauthorized",
                "_errCodeForbidden",
                "_errCodeNotFound",
                "_errCodeConflict",
                "_errCodeInternalErr",
                "_errCodeUnavailable",
                "_errCodeRateLimited"
            ]
        },
        "rest.sendOTPView": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "description": "seconds until the code expires",
                    "type": "integer",
                    "example": 180
                },
                "resend_in": {
                    "description": "seconds until a new code may be requested",
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "rest.statusType": {
            "type": "string",
            "enum": [
                "Success",
                "Failure"
            ],
            "x-enum-varnames": [
                "_statusSuccess",
                "_statusFailure"
            ]
        },
        "rest.userListView": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.userView"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "rest.userView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "7b0c1f1e-2d7a-4d8e-9a55-0f4a0d7f9c11"
                },
                "name": {
                    "type": "string",
                    "example": "Dilnoza"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+998901234567"
                },
                "photo_id": {
                    "type": "string",
                    "example": "3f1d2c4b-8a9e-4b7c-9d2e-1a2b3c4d5e6f"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "dilnoza_95"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminKey": {
            "type": "apiKey",
            "name": "X-Admin-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Birga API",
	Description:      "Backend for the Birga caregiver app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
